default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: <%= "#{ENV.fetch("DATABASE_SCHEMA")}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch("DATABASE_SCHEMA")}_test" %>

production:
  <<: *default
  database: <%= "#{ENV.fetch("DATABASE_SCHEMA")}" %>
