Admin::Admin.create([{ name: 'Sugi', email: 'admin@gmail.com', password: '123456' },
                     { name: 'Sagi', email: 'chinzorigt_saruulgun@unimedia.co.jp', password: 'abc123' }])

Worker::Worker.create([{ name: 'Worker1', email: 'user@gmail.com', password: '123456' },
                       { name: 'Worker2', email: 'example@gmail.com', password: '123456' },
                       { name: 'Sugi', email: 'admin@gmail.com', password: '123456' },
                       { name: 'Sagi', email: 'admin@unimedia.co.jp', password: 'abc123' }])

Worker::Shipment.create([{ code: 's123', name: 'good1', note: 'big', delivery_date: DateTime.now },
                         { code: 's234', name: 'good2', note: 'small', delivery_date: DateTime.now },
                         { code: 's123', name: 'good3', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good4', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good5', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good6', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good7', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good8', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good9', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good10', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good11', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good12', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good13', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good14', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good15', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good16', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good17', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good18', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good19', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good20', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good21', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good22', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good23', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good24', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good25', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good26', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good27', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good28', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good29', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good30', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good31', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good32', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good33', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good34', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good35', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good36', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good37', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good38', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good39', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good40', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good41', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good42', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good43', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good44', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good45', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good46', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good47', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good48', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good49', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good50', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good51', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good52', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good53', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good54', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good55', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good56', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good57', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good58', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good59', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good60', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good61', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good62', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good63', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good64', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good65', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good66', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good67', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good68', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good69', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good70', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good71', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good72', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good73', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good74', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good75', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good76', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good77', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's123', name: 'good78', note: 'urgent!', delivery_date: DateTime.now },
                         { code: 's234', name: 'good79', note: '', delivery_date: DateTime.now }])